os: linux
dist: jammy
language: generic
addons:
  apt:
    packages:
      - libxml-xpath-perl
services:
  - docker

git:
  depth: false

env:
  global:
    - DOCKER_IMAGE_NAME=evmapp
#    - PROD_RELEASE_BRANCH=main
    - TRAVIS_TAG=0.1.0-SNAPSHOT6
    - DEV_RELEASE_BRANCH=buildNeededImage
    #- DEV_RELEASE_BRANCH=development

before_script: source ci/setup_env.sh

jobs:
  include:
    - name: "Evmapp Docker Image Build"
      script: ci/docker.sh
      #if: tag IS present
